version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
