name: Deploy with rsync and sshpass

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass and rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass rsync

    - name: Upload project to VM using rsync (excluding node_modules and .git)
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" rsync -avz \
          --exclude=".git/" \
          --exclude="node_modules/" \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/project

    - name: Setup environment variables and run Docker Compose on VM
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
          set -e
          cd ~/project

          echo "Creating frontend and backend .env files..."

          # Frontend env
          mkdir -p frontend backend
          echo "NEXT_PUBLIC_API_BASE_URL=http://20.193.159.139:3001/" > frontend/.env
          echo "API_BASE_URL=http://20.193.159.139:3001/" >> frontend/.env
          echo "NEXT_PUBLIC_API_BASE_URL=http://20.193.159.139:3001/" > frontend/.env.production
          echo "API_BASE_URL=http://20.193.159.139:3001/" >> frontend/.env.production

          # Backend env
          echo "NODE_ENV=production" > backend/.env
          echo "PORT=3001" >> backend/.env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> backend/.env
          echo "SECRET_HEX=${{ secrets.SECRET_HEX }}" >> backend/.env
          echo "ACCESS_TOKEN_LIFETIME_MIN=60" >> backend/.env
          echo "BCRYPT_N_ROUNDS=12" >> backend/.env
          echo "WHITELIST_ORIGINS=[\\"http://localhost:3000\\"]" >> backend/.env
          echo "SMTP_USER=project" >> backend/.env
          echo "SMTP_PASS=secret" >> backend/.env
          echo "SMTP_PORT=1025" >> backend/.env
          echo "SMTP_HOST=localhost" >> backend/.env
          echo "SMTP_FROM_EMAIL=no-reply@example.com" >> backend/.env


          echo "Starting Backend"
         
          npm install --legacy-peer-deps
          npm run build
          pm2 delete backend || true
          pm2 start dist/server.js --name backend
          
          echo "Starting Frontend"

          cd ../frontend
          npm install
          npm run build
          pm2 delete frontend || true
          pm2 start npm --name frontend -- start
          
          pm2 save
          pm2 startup

        EOF
